### ISSUE TITLE
Mixin：Firefoxメディアクエリの確認

### ISSUE THREAD

**Issue by qrac** [qrac/sass-dashi#6]
`@-moz-document url-prefix()` がFirefox v69 βで効いていない様子。

- https://twitter.com/takamosoo/status/1161054920973250560

本リリースで変更になっていれば該当箇所を修正。

https://github.com/qrac/sass-dashi/blob/master/src/scss/mixin/_mediaquery.scss#L138-L142

**Comment by qrac** [comment]
Firefox 69 リリース

https://codepen.io/qrac/pen/rNBYQrB

```scss
@-moz-document url-prefix() {
  p {
    color: red;
  }
}
```
